version: "3.8"
services:
  auth-db:
    container_name: auth-db
    build: docker/images/db
    volumes:
      - auth_data:/var/lib/postgresql/data/
    ports:
      - "$AUTH_DB_PORT:5432"
    networks:
      - auth

  auth-api:
    container_name: auth-api
    build: docker/images/javascript
    networks:
      - auth
      - common
    volumes:
      - ./src/auth-api:/app
    ports:
      - "$AUTH_API_PORT:80"
    env_file:
      - .env
    environment:
      - USE_DEV_MODE
      - PORT=80

  bl-db:
    container_name: bl-db
    build: docker/images/db
    volumes:
      - bl_data:/var/lib/postgresql/data/
    ports:
      - "$BL_DB_PORT:5432"
    networks:
      - bl

  bl-api:
    container_name: bl-api
    build: docker/images/javascript
    networks:
      - bl
      - common
    volumes:
      - ./src/bl-api:/app
    ports:
      - "$BL_API_PORT:80"
      - "$SWAGGER_PORT:8080"
    env_file:
      - .env
    environment:
      - USE_DEV_MODE
      - PORT=80
      - SWAGGER_PORT=8080
      - DATABASE_URL=postgresql://sd:sd@bl-db:5432/sd?schema=public
      - DB_USER=sd
      - DB_HOST=bl-db
      - DB_NAME=sd
      - DB_PASSWORD=sd
      - DB_PORT=5432

  importer:
    container_name: importer
    build: docker/images/javascript
    networks:
      - bl
    volumes:
      - ./docker/volumes/importer:/data
      - ./src/importer:/app
    environment:
      - USE_DEV_MODE
      - DB_USER=sd
      - DB_HOST=bl-db
      - DB_NAME=sd
      - DB_PASSWORD=sd
      - DB_PORT=5432
    depends_on:
      - bl-db
      - bl-api

  frontend:
    container_name: frontend
    build: docker/images/javascript
    networks:
      - common
    volumes:
      - ./src/web:/app
    ports:
      - "$FRONTEND_PORT:80"
    environment:
      - USE_DEV_MODE
      - PORT=80
      - REACT_APP_API_URL=http://localhost:$BL_API_PORT

networks:
  common:
    driver: bridge 
  auth:
    driver: bridge
  bl:
    driver: bridge

volumes:
  auth_data:
  bl_data:
